### ISSUE TITLE
Some errors when running under V5.0

### ISSUE THREAD

**Issue by zlqs1985** [mcreel/SelectStatisticsABC.jl#1]
Hi, Michael:
    Nice program. However, when I try to run the code under Julia V5.0, some errors emerged,say 
    In `SelectionAlgorithm.jl` line 20 , you define 
    `neighbors = 100. # a float type`
    That cause a "Invalid Index" error
    and

![image](https://cloud.githubusercontent.com/assets/10328230/19773565/9e7aca6e-9c9c-11e6-90d5-c3e89cbde9f5.png)

  among others

**Comment by mcreel** [comment]
Thanks for the heads up. I will fix it soon.

**Comment by mcreel** [comment]
I have committed fixes for the julia 0.5 issues. Thanks again for the warning.
